# Generated by Django 6.0.4 on 2026-05-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Начальник ОТК / Администратор'), ('engineer', 'Специалист ОТиР'), ('technician', 'Рабочий / Слесарь-ремонтник'), ('storekeeper', 'Кладовщик'), ('trainee', 'Ученик / Практикант'), ('seller', 'Продавец')], default='trainee', max_length=20, verbose_name='Роль'),
        ),
    ]
