# Generated by Django 6.0.5 on 2026-05-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Начальник ОТК / Администратор'), ('engineer', 'Специалист ОТиР'), ('technician', 'Рабочий / Слесарь-ремонтник'), ('storekeeper', 'Кладовщик'), ('trainee', 'Ученик / Практикант'), ('seller', 'Продавец'), ('client', 'Клиент')], default='client', max_length=20, verbose_name='Роль'),
        ),
    ]
