# Generated by Django 6.0.4 on 2026-05-05 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('planned', 'Плановое ТО'), ('emergency', 'Аварийный ремонт'), ('modernization', 'Модернизация'), ('inspection', 'Инспекция')], max_length=30, verbose_name='Тип работ')),
                ('priority', models.IntegerField(choices=[(1, 'Критический'), (2, 'Высокий'), (3, 'Средний'), (4, 'Низкий'), (5, 'Отложенный')], default=3, verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('assigned', 'Назначен'), ('in_progress', 'В работе'), ('pending_parts', 'Ожидание запчастей'), ('completed', 'Выполнен'), ('rejected', 'Отклонен')], default='new', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(default='Техническое обслуживание / устранение неисправности', verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало работ')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение работ')),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='equipment.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Наряд-заказ',
                'verbose_name_plural': 'Наряды-заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='Дата отчёта')),
                ('hours_spent', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Затрачено часов')),
                ('description', models.TextField(default='Работы выполнены по регламенту. Замечаний нет.', verbose_name='Описание работ')),
                ('technician_signature', models.CharField(blank=True, max_length=100, null=True, verbose_name='Подпись исполнителя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='workorders.workorder', verbose_name='Наряд-заказ')),
            ],
            options={
                'verbose_name': 'Отчёт о работах',
                'verbose_name_plural': 'Отчёты о работах',
            },
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status'], name='workorders__status_2e2089_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['assigned_user'], name='workorders__assigne_30e9a4_idx'),
        ),
    ]
