# Generated by Django 6.0.5 on 2026-05-06 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('planned', 'Плановое ТО'), ('emergency', 'Аварийный ремонт'), ('modernization', 'Модернизация'), ('inspection', 'Инспекция')], max_length=30, verbose_name='Тип работ')),
                ('priority', models.IntegerField(choices=[(1, 'Критический'), (2, 'Высокий'), (3, 'Средний'), (4, 'Низкий'), (5, 'Отложенный')], default=3, verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('assigned', 'Назначен'), ('in_progress', 'В работе'), ('pending_parts', 'Ожидание запчастей'), ('completed', 'Выполнен'), ('rejected', 'Отклонен')], default='new', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(default='Техническое обслуживание / устранение неисправности', verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало работ')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение работ')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Плановые часы')),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Фактические часы')),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Плановая стоимость')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Фактическая стоимость')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Место выполнения')),
                ('safety_measures', models.TextField(blank=True, null=True, verbose_name='Меры безопасности')),
                ('completion_notes', models.TextField(blank=True, null=True, verbose_name='Комментарий о завершении')),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='equipment.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Наряд-заказ',
                'verbose_name_plural': 'Наряды-заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('start', 'Начало работы'), ('pause', 'Пауза'), ('resume', 'Возобновление'), ('complete', 'Завершение этапа'), ('note', 'Заметка'), ('issue', 'Проблема')], max_length=20, verbose_name='Тип записи')),
                ('description', models.TextField(verbose_name='Описание')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (мин)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Техник')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='workorders.workorder', verbose_name='Наряд-заказ')),
            ],
            options={
                'verbose_name': 'Запись журнала работ',
                'verbose_name_plural': 'Журнал работ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='work_attachments/%Y/%m/%d/', verbose_name='Файл')),
                ('attachment_type', models.CharField(choices=[('photo', 'Фотография'), ('document', 'Документ'), ('diagram', 'Схема'), ('manual', 'Руководство'), ('act', 'Акт'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип вложения')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('file_size', models.PositiveIntegerField(help_text='Размер в байтах', verbose_name='Размер файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='workorders.workorder', verbose_name='Наряд-заказ')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('notification_type', models.CharField(choices=[('task', 'Задание'), ('message', 'Сообщение'), ('alert', 'Предупреждение'), ('reminder', 'Напоминание')], default='task', max_length=20, verbose_name='Тип уведомления')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('read', 'Прочитано'), ('accepted', 'Взято в работу'), ('in_progress', 'Выполняется'), ('done', 'Выполнено')], default='pending', max_length=20, verbose_name='Статус')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата прочтения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Отправил')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Работник')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workorders.workorder', verbose_name='Наряд-заказ')),
            ],
            options={
                'verbose_name': 'Уведомление о задаче',
                'verbose_name_plural': 'Уведомления о задачах',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Изменён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_order_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='workorders.workordercomment', verbose_name='Ответ на комментарий')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workorders.workorder', verbose_name='Наряд-заказ')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оценка качества')),
                ('timeliness_score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оценка своевременности')),
                ('professionalism_score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оценка профессионализма')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки')),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Оценивший')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='workorders.workorder', verbose_name='Наряд-заказ')),
            ],
            options={
                'verbose_name': 'Оценка работы',
                'verbose_name_plural': 'Оценки работ',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20, verbose_name='Старый статус')),
                ('new_status', models.CharField(max_length=20, verbose_name='Новый статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к изменению')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='workorders.workorder', verbose_name='Наряд-заказ')),
            ],
            options={
                'verbose_name': 'История статуса',
                'verbose_name_plural': 'Истории статусов',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='Дата отчёта')),
                ('hours_spent', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Затрачено часов')),
                ('description', models.TextField(default='Работы выполнены по регламенту. Замечаний нет.', verbose_name='Описание работ')),
                ('technician_signature', models.CharField(blank=True, max_length=100, null=True, verbose_name='Подпись исполнителя')),
                ('quality_rating', models.IntegerField(choices=[(1, 'Неудовлетворительно'), (2, 'Плохо'), (3, 'Удовлетворительно'), (4, 'Хорошо'), (5, 'Отлично')], default=3, verbose_name='Оценка качества')),
                ('parts_used', models.TextField(blank=True, null=True, verbose_name='Использованные запчасти')),
                ('issues_found', models.TextField(blank=True, null=True, verbose_name='Выявленные проблемы')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='Рекомендации')),
                ('photos', models.JSONField(blank=True, null=True, verbose_name='Фотоотчёт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='workorders.workorder', verbose_name='Наряд-заказ')),
            ],
            options={
                'verbose_name': 'Отчёт о работах',
                'verbose_name_plural': 'Отчёты о работах',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('description', models.TextField(verbose_name='Описание')),
                ('equipment_type', models.CharField(max_length=50, verbose_name='Тип оборудования')),
                ('checklist', models.TextField(default='', verbose_name='Чек-лист работ')),
                ('estimated_hours', models.DecimalField(decimal_places=1, default=1.0, max_digits=5, verbose_name='Плановые часы')),
                ('required_parts', models.TextField(blank=True, null=True, verbose_name='Необходимые запчасти')),
                ('safety_requirements', models.TextField(blank=True, null=True, verbose_name='Требования безопасности')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Шаблон работ',
                'verbose_name_plural': 'Шаблоны работ',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status'], name='workorders__status_2e2089_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['assigned_user'], name='workorders__assigne_30e9a4_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['priority'], name='workorders__priorit_226700_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['created_at'], name='workorders__created_243b85_idx'),
        ),
        migrations.AddIndex(
            model_name='tasknotification',
            index=models.Index(fields=['worker', 'is_read'], name='workorders__worker__cd193f_idx'),
        ),
        migrations.AddIndex(
            model_name='tasknotification',
            index=models.Index(fields=['status'], name='workorders__status_c1a5e8_idx'),
        ),
        migrations.AddIndex(
            model_name='workordercomment',
            index=models.Index(fields=['work_order', 'created_at'], name='workorders__work_or_09f7b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workorderrating',
            unique_together={('work_order', 'rated_by')},
        ),
    ]
