# Generated by Django 6.0.5 on 2026-05-06 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('read', 'Прочитано'), ('accepted', 'Взято в работу'), ('in_progress', 'Выполняется'), ('done', 'Выполнено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Отправил')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workorders.workorder', verbose_name='Наряд-заказ')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Уведомление о задаче',
                'verbose_name_plural': 'Уведомления о задачах',
                'ordering': ['-created_at'],
            },
        ),
    ]
