# Generated by Django 6.0.4 on 2026-05-05 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workorders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=30, unique=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Категория')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за ед.')),
                ('min_stock', models.PositiveIntegerField(default=5, verbose_name='Мин. остаток')),
                ('current_stock', models.PositiveIntegerField(default=0, verbose_name='Текущий остаток')),
                ('warehouse_location', models.CharField(blank=True, max_length=30, null=True, verbose_name='Место на складе')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Запчасть',
                'verbose_name_plural': 'Запчасти',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='PartRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('status', models.CharField(choices=[('requested', 'Запрошено'), ('approved', 'Утверждено'), ('issued', 'Выдано'), ('rejected', 'Отклонено')], default='requested', max_length=20, verbose_name='Статус')),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('fulfilled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_parts', to=settings.AUTH_USER_MODEL, verbose_name='Выдал')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_parts', to=settings.AUTH_USER_MODEL, verbose_name='Запросил')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_requests', to='workorders.workorder', verbose_name='Наряд-заказ')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='inventory.sparepart', verbose_name='Запчасть')),
            ],
            options={
                'verbose_name': 'Заявка на запчасти',
                'verbose_name_plural': 'Заявки на запчасти',
                'ordering': ['-id'],
            },
        ),
    ]
