# Generated by Django 6.0.5 on 2026-05-06 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0002_initial'),
        ('workorders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Контактное лицо')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Сайт')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='Рейтинг')),
                ('payment_terms', models.CharField(blank=True, max_length=200, null=True, verbose_name='Условия оплаты')),
                ('delivery_time_days', models.PositiveIntegerField(default=7, verbose_name='Срок поставки (дней)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Номер заказа')),
                ('order_date', models.DateField(verbose_name='Дата заказа')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='Ожидаемая дата доставки')),
                ('actual_delivery_date', models.DateField(blank=True, null=True, verbose_name='Фактическая дата доставки')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('confirmed', 'Подтверждён'), ('partial', 'Частично получен'), ('received', 'Получен'), ('cancelled', 'Отменён')], default='draft', max_length=20, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая сумма')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='inventory.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Заказ на поставку',
                'verbose_name_plural': 'Заказы на поставку',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=30, unique=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('category', models.CharField(choices=[('bearings', 'Подшипники'), ('seals', 'Уплотнения'), ('filters', 'Фильтры'), ('belts', 'Ремни'), ('electrical', 'Электрика'), ('hydraulic', 'Гидравлика'), ('pneumatic', 'Пневматика'), ('fasteners', 'Крепёж'), ('lubricants', 'Смазочные материалы'), ('tools', 'Инструмент'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Категория')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за ед.')),
                ('min_stock', models.PositiveIntegerField(default=5, verbose_name='Мин. остаток')),
                ('current_stock', models.PositiveIntegerField(default=0, verbose_name='Текущий остаток')),
                ('reserved_stock', models.PositiveIntegerField(default=0, verbose_name='Зарезервировано')),
                ('warehouse_location', models.CharField(blank=True, max_length=30, null=True, verbose_name='Место на складе')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('supplier', models.CharField(blank=True, max_length=200, null=True, verbose_name='Поставщик')),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Производитель')),
                ('lead_time_days', models.PositiveIntegerField(default=7, verbose_name='Срок поставки (дней)')),
                ('reorder_quantity', models.PositiveIntegerField(default=10, verbose_name='Количество для заказа')),
                ('last_purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата последней закупки')),
                ('last_purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена последней закупки')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Штрих-код')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='spare_parts/%Y/%m/%d/', verbose_name='Фото')),
                ('datasheet', models.FileField(blank=True, null=True, upload_to='spare_parts_docs/%Y/%m/%d/', verbose_name='Спецификация')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('compatible_equipment', models.ManyToManyField(blank=True, related_name='compatible_parts', to='equipment.equipment', verbose_name='Совместимое оборудование')),
            ],
            options={
                'verbose_name': 'Запчасть',
                'verbose_name_plural': 'Запчасти',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.PositiveIntegerField(verbose_name='Заказано')),
                ('quantity_received', models.PositiveIntegerField(default=0, verbose_name='Получено')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за ед.')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Общая стоимость')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата получения')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseorder', verbose_name='Заказ')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.sparepart', verbose_name='Запчасть')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
        migrations.CreateModel(
            name='PartRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.PositiveIntegerField(verbose_name='Запрошено')),
                ('quantity_issued', models.PositiveIntegerField(default=0, verbose_name='Выдано')),
                ('status', models.CharField(choices=[('requested', 'Запрошено'), ('approved', 'Утверждено'), ('issued', 'Выдано'), ('rejected', 'Отклонено'), ('partially_issued', 'Частично выдано')], default='requested', max_length=20, verbose_name='Статус')),
                ('priority', models.IntegerField(choices=[(1, 'Срочно'), (2, 'Высокий'), (3, 'Обычный'), (4, 'Низкий')], default=3, verbose_name='Приоритет')),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Причина отказа')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_parts', to=settings.AUTH_USER_MODEL, verbose_name='Утвердил')),
                ('fulfilled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_parts', to=settings.AUTH_USER_MODEL, verbose_name='Выдал')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_parts', to=settings.AUTH_USER_MODEL, verbose_name='Запросил')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_requests', to='workorders.workorder', verbose_name='Наряд-заказ')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='inventory.sparepart', verbose_name='Запчасть')),
            ],
            options={
                'verbose_name': 'Заявка на запчасти',
                'verbose_name_plural': 'Заявки на запчасти',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('receipt', 'Приход'), ('issue', 'Расход'), ('adjustment', 'Корректировка'), ('return', 'Возврат'), ('write_off', 'Списание'), ('transfer', 'Перемещение')], max_length=20, verbose_name='Тип операции')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена за ед.')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Общая сумма')),
                ('stock_before', models.PositiveIntegerField(verbose_name='Остаток до')),
                ('stock_after', models.PositiveIntegerField(verbose_name='Остаток после')),
                ('reference_document', models.CharField(blank=True, max_length=100, null=True, verbose_name='Документ основание')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Выполнил')),
                ('related_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='inventory.partrequest', verbose_name='Заявка')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.sparepart', verbose_name='Запчасть')),
            ],
            options={
                'verbose_name': 'Операция с запчастями',
                'verbose_name_plural': 'Операции с запчастями',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sparepart',
            index=models.Index(fields=['category'], name='inventory_s_categor_fd5cdf_idx'),
        ),
        migrations.AddIndex(
            model_name='sparepart',
            index=models.Index(fields=['current_stock'], name='inventory_s_current_77864a_idx'),
        ),
        migrations.AddIndex(
            model_name='sparepart',
            index=models.Index(fields=['is_active'], name='inventory_s_is_acti_fef96e_idx'),
        ),
        migrations.AddIndex(
            model_name='partrequest',
            index=models.Index(fields=['status'], name='inventory_p_status_e26656_idx'),
        ),
        migrations.AddIndex(
            model_name='partrequest',
            index=models.Index(fields=['priority'], name='inventory_p_priorit_7d4c98_idx'),
        ),
        migrations.AddIndex(
            model_name='partrequest',
            index=models.Index(fields=['created_at'], name='inventory_p_created_eac9d6_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['transaction_type'], name='inventory_i_transac_2eccee_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['created_at'], name='inventory_i_created_670884_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['spare_part', 'created_at'], name='inventory_i_spare_p_c621b2_idx'),
        ),
    ]
