# Generated by Django 6.0.4 on 2026-05-05 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_number', models.CharField(max_length=30, unique=True, verbose_name='Инвентарный номер')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('type', models.CharField(choices=[('Насосы', 'Насосы'), ('Компрессоры', 'Компрессоры'), ('Электропривод', 'Электропривод'), ('Механика', 'Механика'), ('Вентиляция', 'Вентиляция'), ('Транспорт', 'Транспорт'), ('Металлообработка', 'Металлообработка'), ('Энергетика', 'Энергетика'), ('Электрика', 'Электрика'), ('Автоматика', 'Автоматика')], max_length=50, verbose_name='Тип оборудования')),
                ('workshop', models.CharField(max_length=50, verbose_name='Цех/Участок')),
                ('status', models.CharField(choices=[('active', 'В эксплуатации'), ('maintenance', 'На обслуживании'), ('out_of_service', 'Неисправно'), ('decommissioned', 'Списано')], default='active', max_length=20, verbose_name='Статус')),
                ('install_date', models.DateField(blank=True, null=True, verbose_name='Дата установки')),
                ('warranty_until', models.DateField(blank=True, null=True, verbose_name='Гарантия до')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='Последнее ТО')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['inv_number'],
                'indexes': [models.Index(fields=['status'], name='equipment_e_status_fb8540_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_days', models.PositiveIntegerField(verbose_name='Периодичность (дней)')),
                ('next_due', models.DateField(verbose_name='Следующее ТО')),
                ('last_completed', models.DateField(blank=True, null=True, verbose_name='Последнее выполненное')),
                ('checklist', models.TextField(default='Проверка масла, натяжение, очистка фильтров, смазка, замер вибрации', verbose_name='Чек-лист')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='equipment.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'График ТО',
                'verbose_name_plural': 'Графики ТО',
            },
        ),
    ]
