# Generated by Django 6.0.5 on 2026-05-06 11:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentMeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_type', models.CharField(choices=[('hours', 'Моточасы'), ('cycles', 'Циклы'), ('kilometers', 'Километры'), ('units', 'Единицы продукции'), ('pressure', 'Давление'), ('temperature', 'Температура'), ('vibration', 'Вибрация'), ('other', 'Другое')], max_length=20, verbose_name='Тип показания')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Значение')),
                ('unit', models.CharField(default='', max_length=20, verbose_name='Единица измерения')),
                ('reading_date', models.DateTimeField(verbose_name='Дата показания')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Показание счётчика',
                'verbose_name_plural': 'Показания счётчиков',
                'ordering': ['-reading_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_days', models.PositiveIntegerField(verbose_name='Периодичность (дней)')),
                ('frequency_type', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно'), ('quarterly', 'Ежеквартально'), ('semi_annual', 'Полугодово'), ('annual', 'Ежегодно'), ('custom', 'По наработке')], default='monthly', max_length=20, verbose_name='Тип периодичности')),
                ('next_due', models.DateField(verbose_name='Следующее ТО')),
                ('last_completed', models.DateField(blank=True, null=True, verbose_name='Последнее выполненное')),
                ('checklist', models.TextField(default='Проверка масла, натяжение, очистка фильтров, смазка, замер вибрации', verbose_name='Чек-лист')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('estimated_duration_hours', models.DecimalField(decimal_places=1, default=1.0, max_digits=4, verbose_name='Плановая длительность (час)')),
                ('required_specialists', models.CharField(blank=True, max_length=200, null=True, verbose_name='Требуемые специалисты')),
                ('required_parts', models.TextField(blank=True, null=True, verbose_name='Необходимые запчасти')),
                ('safety_requirements', models.TextField(blank=True, null=True, verbose_name='Требования безопасности')),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Плановая стоимость')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'График ТО',
                'verbose_name_plural': 'Графики ТО',
                'ordering': ['next_due'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_number', models.CharField(max_length=30, unique=True, verbose_name='Инвентарный номер')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('type', models.CharField(choices=[('Насосы', 'Насосы'), ('Компрессоры', 'Компрессоры'), ('Электропривод', 'Электропривод'), ('Механика', 'Механика'), ('Вентиляция', 'Вентиляция'), ('Транспорт', 'Транспорт'), ('Металлообработка', 'Металлообработка'), ('Энергетика', 'Энергетика'), ('Электрика', 'Электрика'), ('Автоматика', 'Автоматика')], max_length=50, verbose_name='Тип оборудования')),
                ('workshop', models.CharField(max_length=50, verbose_name='Цех/Участок')),
                ('status', models.CharField(choices=[('active', 'В эксплуатации'), ('maintenance', 'На обслуживании'), ('out_of_service', 'Неисправно'), ('decommissioned', 'Списано')], default='active', max_length=20, verbose_name='Статус')),
                ('install_date', models.DateField(blank=True, null=True, verbose_name='Дата установки')),
                ('warranty_until', models.DateField(blank=True, null=True, verbose_name='Гарантия до')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='Последнее ТО')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Производитель')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Модель')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Серийный номер')),
                ('criticality', models.IntegerField(choices=[(1, 'Критическое'), (2, 'Важное'), (3, 'Стандартное'), (4, 'Вспомогательное')], default=3, verbose_name='Критичность')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена покупки')),
                ('replacement_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость замены')),
                ('expected_lifetime_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок службы (лет)')),
                ('location_details', models.CharField(blank=True, max_length=200, null=True, verbose_name='Детали расположения')),
                ('technical_specs', models.TextField(blank=True, null=True, verbose_name='Технические характеристики')),
                ('manual_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на руководство')),
                ('qr_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='QR-код')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Штрих-код')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('parent_equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_equipment', to='equipment.equipment', verbose_name='Родительское оборудование')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_equipment', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['inv_number'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('status', 'Изменение статуса'), ('location', 'Изменение места'), ('assignment', 'Изменение ответственного'), ('modification', 'Модификация'), ('repair', 'Ремонт'), ('inspection', 'Инспекция'), ('other', 'Другое')], max_length=20, verbose_name='Тип изменения')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='Новое значение')),
                ('description', models.TextField(verbose_name='Описание изменения')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='equipment.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Запись журнала изменений',
                'verbose_name_plural': 'Журнал изменений',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('manual', 'Руководство'), ('passport', 'Паспорт'), ('certificate', 'Сертификат'), ('diagram', 'Схема'), ('specification', 'Спецификация'), ('protocol', 'Протокол'), ('act', 'Акт'), ('other', 'Другое')], max_length=20, verbose_name='Тип документа')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('file', models.FileField(upload_to='equipment_docs/%Y/%m/%d/', verbose_name='Файл')),
                ('file_size', models.PositiveIntegerField(help_text='Размер в байтах', verbose_name='Размер файла')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('version', models.CharField(blank=True, max_length=20, null=True, verbose_name='Версия')),
                ('is_current', models.BooleanField(default=True, verbose_name='Актуальная версия')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='equipment.equipment', verbose_name='Оборудование')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Документ оборудования',
                'verbose_name_plural': 'Документы оборудования',
                'ordering': ['equipment', '-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateTimeField(verbose_name='Дата отказа')),
                ('failure_type', models.CharField(choices=[('mechanical', 'Механический'), ('electrical', 'Электрический'), ('hydraulic', 'Гидравлический'), ('pneumatic', 'Пневматический'), ('software', 'Программный'), ('operator_error', 'Ошибка оператора'), ('wear_out', 'Износ'), ('other', 'Другое')], max_length=20, verbose_name='Тип отказа')),
                ('severity', models.IntegerField(choices=[(1, 'Критический'), (2, 'Высокий'), (3, 'Средний'), (4, 'Низкий')], verbose_name='Серьёзность')),
                ('description', models.TextField(verbose_name='Описание отказа')),
                ('root_cause', models.TextField(blank=True, null=True, verbose_name='Причина отказа')),
                ('corrective_action', models.TextField(blank=True, null=True, verbose_name='Предпринятые действия')),
                ('downtime_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Время простоя (час)')),
                ('repair_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость ремонта')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата устранения')),
                ('photos', models.JSONField(blank=True, null=True, verbose_name='Фотоотчёт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failures', to='equipment.equipment', verbose_name='Оборудование')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_failures', to=settings.AUTH_USER_MODEL, verbose_name='Сообщил')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_failures', to=settings.AUTH_USER_MODEL, verbose_name='Устранил')),
            ],
            options={
                'verbose_name': 'Отказ оборудования',
                'verbose_name_plural': 'Отказы оборудования',
                'ordering': ['-failure_date'],
            },
        ),
    ]
