# Generated by Django 6.0.5 on 2026-05-06 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('workorders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentfailure',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_failures', to='workorders.workorder', verbose_name='Наряд-заказ'),
        ),
        migrations.AddField(
            model_name='equipmentmeterreading',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='equipment.equipment', verbose_name='Оборудование'),
        ),
        migrations.AddField(
            model_name='equipmentmeterreading',
            name='taken_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Снял'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='equipment.equipment', verbose_name='Оборудование'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['status'], name='equipment_e_status_fb8540_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['type'], name='equipment_e_type_e5b2aa_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['criticality'], name='equipment_e_critica_2dbecd_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['workshop'], name='equipment_e_worksho_c0ddc9_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentfailure',
            index=models.Index(fields=['failure_date'], name='equipment_e_failure_a61301_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentfailure',
            index=models.Index(fields=['severity'], name='equipment_e_severit_945f55_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentfailure',
            index=models.Index(fields=['equipment', 'failure_date'], name='equipment_e_equipme_4ca0c2_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentmeterreading',
            index=models.Index(fields=['equipment', 'reading_date'], name='equipment_e_equipme_5cd29c_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentmeterreading',
            index=models.Index(fields=['reading_type'], name='equipment_e_reading_edfd12_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceschedule',
            index=models.Index(fields=['next_due'], name='equipment_m_next_du_46cdf7_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceschedule',
            index=models.Index(fields=['is_active'], name='equipment_m_is_acti_18d8aa_idx'),
        ),
    ]
